stages: 
    - build
    - test

buildJob:
    stage: build
    script:
        - pip3 install -r requirements.txt
        - cd frontend/ 
        - cnpm install
        - cnpm run build

testJob:
    stage: test
    script:
        - cd frontend/
        - cnpm install
        - cnpm run unit
        - cd ..
        - python3 ./manage.py test
